language: julia
os:
  - linux
#  - osx
julia:
  - 0.6
  - 0.7
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Showoff")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
